### PR TITLE
fix: Remove unnecessary request

### LINKED ISSUE #320: Remove unnecessary request
When drawing annotation, request to link_category should be sent only if selected category has taxonomy data attribute
image

### PR DESCRIPTION
**Pull request by Aleksei-Egorenko-EPAM**
Closes #320

### CODE REVIEW

**Review by sbilevich — APPROVED** [review]

File: web/src/components/task/task-sidebar/task-sidebar.tsx [hunk 1]
```diff
@@ -268,10 +269,19 @@ const TaskSidebar: FC<TaskSidebarProps> = ({ onRedirectAfterFinish, jobSettings,
...
+    if (
+        selectedCategory &&
+        Array.isArray(selectedCategory.data_attributes) &&
+        selectedCategory.data_attributes.some((category) => category.type === 'taxonomy')
+    ) {
+        taxonomy = useLinkTaxonomyByCategoryAndJobId({
+            jobId,
+            categoryId: selectedAnnotation?.category!
+        });
+    } else {
```
Comment (Iogsotot) [inline web/src/components/task/task-sidebar/task-sidebar.tsx:282]: what purpose are you using this `else` statement for?

File: web/src/components/task/task-sidebar/task-sidebar.tsx [hunk 2]
```diff
@@ -268,10 +269,19 @@ const TaskSidebar: FC<TaskSidebarProps> = ({ onRedirectAfterFinish, jobSettings,
...
+        taxonomy = undefined;
```
Comment (Iogsotot) [inline web/src/components/task/task-sidebar/task-sidebar.tsx:283]: I suppose assigning the value "undefined" manually is not a good practice
https://learn.javascript.ru/types#:~:text=%E2%80%A6%D0%9D%D0%BE%20%D1%82%D0%B0%D0%BA%20%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C%20%D0%BD%D0%B5%20%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F

Comment (Aleksei-Egorenko-EPAM) [reply web/src/components/task/task-sidebar/task-sidebar.tsx:283]: redefined to undefined to properly fire this condition(482/492 taxonomyId={(taxonomy?.data || [])[0]?.id}) when choosing a non-taxonomy option
